export default{
    SIGNIN:{
        path:'/user/signin',
        auth:false
    },
    SIGNUP:{
        path:'/user/signup',
        auth:false
    },
    FORGOT_PASSWORD:{
        path:'/user/forgotpwd',
        auth:false
    },
    RESET_PASSWORD:{
        path:'/user/resetpwd',
        auth:false
    },
    GET_ALL_USERS:{
        path:'/user/get',
        auth:true
    },
    ACTIVATE_NEW_ACCOUNT:{
        path:'/user/activate',
        auth:false
    },
    GET_USER_BY_ID:{
        path:'/user/getuser',
        auth:true
    },
    CHANGE_STATUS:{
        path:'/user/changestatus',
        auth:true
    },
    UPDATE_USER_DETAILS:{
        path:'/user/update',
        auth:true
    },
    ADD_BOOKS:{
        path:'/book/create',
        auth:true
    },
    GET_ALL_BOOKS:{
        path:'/book/getall',
        auth:false
    },
    GET_BOOK_BY_ID:{
        path:'/book/getBook',
        auth:true
    },
    UPDATE_BOOK_BY_ID:{
        path:'/book/update',
        auth:true
    },
    DELETE_BOOK_BY_ID:{
        path:'/book/delete',
        auth:true
    },
    GET_REVIEWS_BY_ID:{
        path:'/review/get',
        auth:false
    },
    ADD_REVIEW:{
        path:'/review/add',
        auth:false
    },
    UPDATE_REVIEW:{
        path:'/review/update',
        auth:true
    },
    
    DELETE_REVIEW:{
        path:'/review/delete',
        auth:true
    },
    ADD_BORROW_BOOK:{
        path:'/borrow/add',
        auth:true
    },
    GET_BORROWBOOK_BY_ID:{
        path:'/borrow/book',
        auth:true
    },
    GET_ALL_BORROWED_BOOKS:{
        path:'/borrow/books',
        auth:true
    },
    RETURN_BOOK:{
        path:'/borrow/return',
        auth:true
    },
    RESERVE_BOOK:{
        path:'/reserve/add',
        auth:true
    },
    GET_RESERVEBOOK_BY_ID:{
        path:'/reserve/get',
        auth:true
    },
    OVER_DUE:{
        path:'/borrow/overdue',
        auth:true
    }
    
    

    

}